pipeline:
  name: bitrise-android-lint
  identifier: bitriseandroidlint
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: android-testing
        build: <+input>
  stages:
    - stage:
        name: linux-amd64
        identifier: linuxamd64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Bitrise
                  name: Android Lint
                  identifier: Android_Lint
                  spec:
                    uses: github.com/bitrise-steplib/bitrise-step-android-build.git
                    with:
                      variant: "'debug'"
                      build_type: "'apk'"
